### ISSUE TITLE
Visually appealing design and content which reflects the venue's atmosphere

### ISSUE THREAD

**Issue by ElFalch** [ElFalch/lund-farm#1]
** User Story ** 

As a person who is engaged to be married and looking for a wedding venue, I want to know what this venue is like. 

** Acceptance Criteria ** 

- [x]  Visually appealing colours and fonts. 
- [x] A clear, inviting design. 

** Tasks ** 

- [x] Use appropriate colours and fonts to convey the atmosphere of the venue. 
- [x] Use space effectively, without overcrowding.
