### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by ElFalch** [ElFalch/lund-farm#3]
** User Story ** 

As a wedding planner, I want to be able to get in touch with this venue. 

** Acceptance Criteria ** 

- [x] A clearly-presented contact form page which confirms submission. 
- [x] a button on the home page header which takes you directly to the contact form. 

** Tasks ** 

- [x] Use Bootstrap forms to create a contact form where uses input their email and a message and are notified of successful submission afterwards. 
- [x] Use bootstrap to add a contact form button which is clearly visible, fits in with the style of the rest of the site
