### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by ElFalch** [ElFalch/lund-farm#5]
** User Story **

As an engaged person who is interested in this venue, I would like to be able to easily find the relevant social media profiles. 

** Acceptance Criteria **

- [x] A clearly presented section with links to social media on each page of the website. 

** Tasks ** 

- [x] Create a footer section with links to each social media profile that incorporates Font Awesome icons. 
- [x] Use the bootstrap grid structure to allow for responsive design across all devices.
