### ISSUE TITLE
attractive Images

### ISSUE THREAD

**Issue by ElFalch** [ElFalch/lund-farm#7]
**User Stories** 

As an engaged person looking for a wedding venue, I want to see lots of attractive images of the venue. 

**Acceptance criteria**

- [x] An image at the top of the home page that draws people in. 
- [x] A gallery page with attractive images that are easy to browse across all device sizes. 
- [x] Images break up large areas of text/ blank space. 

**Tasks**

- [x] Choose an attractive main image for the home page header that mirrors the website's colour scheme. 
- [x] Create a gallery page with aesthetically-pleasing images in a bootstrap carousel. 
- [x] Include an image for each of the services cards on the home page.
- [x] Include an image on the thanks page that users are directed to after submitting the contact form.
